### ISSUE TITLE
Tracking: Image centos/python-35-centos broken

### ISSUE THREAD

**Issue by vpavlin** [jupyter-on-openshift/jupyterhub-quickstart#4]
I've noticed I cannot run jupyterhub anymore due to error described in https://github.com/sclorg/s2i-python-container/issues/246

Upgrade to 3.6 brings in different error 

```
+ exec jupyterhub -f /opt/app-root/etc/jupyterhub_config.py
Traceback (most recent call last):
  File "/opt/app-root/bin/jupyterhub", line 3, in <module>
    from jupyterhub.app import main
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/app.py", line 118, in <module>
    class NewToken(Application):
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/app.py", line 134, in NewToken
    name = Unicode(getuser())
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000930000'
```

**Comment by GrahamDumpleton** [comment]
If this is the case they must have just updated it and broken something. :-(

Will look at this morning.

**Comment by GrahamDumpleton** [comment]
Closing as solution found in linked issue.
